server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.html index.php;

    location = / {
        return 301 $scheme://$http_host/cdn/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location /cdn/ {
        alias /var/www/html/cdn/;
        index index.html;
    }

    location /gm/ {
        alias /var/www/html/gm/;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|json|xml)$ {
        expires max;
        log_not_found off;
    }
}
