_adventure_Info = {
	Root = {
		[1] = {
			functionid = {
				[1] = {functionid = 425,},
			},
			adventure = {
				[1] = {change = 10,cdTime = 60,npcscene = 6008,npcPosition = [[36,244.1]],npc = 21001,targetnpc = 21002,radii = 4,
					map = {
						[1] = {minlev = 1,uplev = 70,scene = [[6006,6007,6008]],},
						[2] = {minlev = 71,uplev = 110,scene = [[6006,6007,6008,6009]],},
						[3] = {minlev = 111,uplev = 200,scene = [[6006,6007,6008,6009,6010,6011,6015]],},
					},
					position = {
						[1] = {scene = 6006,pos = [[57,76]],
							random = {
								[1] = {position = [[54,70]],},
								[2] = {position = [[52,55]],},
								[3] = {position = [[52,39]],},
								[4] = {position = [[50,28]],},
								[5] = {position = [[33,44]],},
								[6] = {position = [[83,99]],},
								[7] = {position = [[98,117]],},
								[8] = {position = [[100,64]],},
								[9] = {position = [[102,39]],},
								[10] = {position = [[110,45]],},
								[11] = {position = [[134,50]],},
								[12] = {position = [[150,75]],},
								[13] = {position = [[155,130]],},
							},
						},
						[2] = {scene = 6007,pos = [[48,66]],
							random = {
								[1] = {position = [[29,88]],},
								[2] = {position = [[57,102]],},
								[3] = {position = [[62,159]],},
								[4] = {position = [[44,50]],},
								[5] = {position = [[56,46]],},
								[6] = {position = [[68,17]],},
								[7] = {position = [[97,64]],},
								[8] = {position = [[104,61]],},
								[9] = {position = [[113,108]],},
								[10] = {position = [[42,63]],},
							},
						},
						[3] = {scene = 6008,pos = [[149,168]],
							random = {
								[1] = {position = [[286,179]],},
								[2] = {position = [[250,240]],},
								[3] = {position = [[192,372]],},
								[4] = {position = [[211,340]],},
								[5] = {position = [[172,317]],},
							},
						},
						[4] = {scene = 6009,pos = [[45,126]],
							random = {
								[1] = {position = [[38,112]],},
								[2] = {position = [[29,87]],},
								[3] = {position = [[43,57]],},
								[4] = {position = [[78,61]],},
								[5] = {position = [[95,108]],},
								[6] = {position = [[110,87]],},
								[7] = {position = [[103,39]],},
								[8] = {position = [[117,231]],},
								[9] = {position = [[125,261]],},
								[10] = {position = [[139,288]],},
								[11] = {position = [[65,202]],},
								[12] = {position = [[26,225]],},
							},
						},
						[5] = {scene = 6010,pos = [[30,269]],
							random = {
								[1] = {position = [[25,260]],},
								[2] = {position = [[37,287]],},
								[3] = {position = [[82,248]],},
								[4] = {position = [[53,204]],},
								[5] = {position = [[35,195]],},
								[6] = {position = [[41,165]],},
								[7] = {position = [[63,117]],},
								[8] = {position = [[122,93]],},
								[9] = {position = [[137,128]],},
							},
						},
						[6] = {scene = 6011,pos = [[98,109]],
							random = {
								[1] = {position = [[66,33]],},
								[2] = {position = [[62,30]],},
								[3] = {position = [[84,26]],},
								[4] = {position = [[90,49]],},
								[5] = {position = [[93,55]],},
								[6] = {position = [[111,98]],},
								[7] = {position = [[114,101]],},
								[8] = {position = [[105,105]],},
								[9] = {position = [[96,111]],},
								[10] = {position = [[61,82]],},
								[11] = {position = [[49,88]],},
								[12] = {position = [[41,95]],},
								[13] = {position = [[35,84]],},
							},
						},
						[7] = {scene = 6015,pos = [[37,174]],
							random = {
								[1] = {position = [[49,55]],},
								[2] = {position = [[17,68]],},
								[3] = {position = [[15,50]],},
								[4] = {position = [[34,130]],},
								[5] = {position = [[42,136]],},
								[6] = {position = [[45,152]],},
								[7] = {position = [[37,159]],},
								[8] = {position = [[44,239]],},
								[9] = {position = [[58,243]],},
								[10] = {position = [[69,233]],},
								[11] = {position = [[71,214]],},
								[12] = {position = [[79,197]],},
								[13] = {position = [[80,181]],},
								[14] = {position = [[85,158]],},
								[15] = {position = [[92,148]],},
								[16] = {position = [[95,135]],},
								[17] = {position = [[88,110]],},
								[18] = {position = [[99,120]],},
								[19] = {position = [[114,121]],},
								[20] = {position = [[116,111]],},
								[21] = {position = [[104,225]],},
							},
						},
					},
					midway = {
						[1] = {mintime = 15,maxtime = 40,
							midevent = {
								[1] = {id = 1,type = 1,buff = [[]],scene = [[]],Position = [[]],textbox = [[]],weight = 5000,},
								[2] = {id = 2,type = 2,buff = 90009,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高80%)]],weight = 100,},
								[3] = {id = 3,type = 2,buff = 90010,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高70%)]],weight = 100,},
								[4] = {id = 4,type = 2,buff = 90011,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高60%)]],weight = 100,},
								[5] = {id = 5,type = 2,buff = 90012,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高50%)]],weight = 100,},
								[6] = {id = 6,type = 2,buff = 90013,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高40%)]],weight = 100,},
								[7] = {id = 7,type = 2,buff = 90014,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高30%)]],weight = 100,},
								[8] = {id = 8,type = 2,buff = 90015,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高20%)]],weight = 100,},
								[9] = {id = 9,type = 2,buff = 90016,scene = [[]],Position = [[]],textbox = [[遇到无名仙人，仙人赐予了你一份加速灵药（60秒内速度提高10%)]],weight = 100,},
								[10] = {id = 10,type = 2,buff = 90017,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了80%)]],weight = 100,},
								[11] = {id = 11,type = 2,buff = 90018,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了70%)]],weight = 100,},
								[12] = {id = 12,type = 2,buff = 90019,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了60%)]],weight = 100,},
								[13] = {id = 13,type = 2,buff = 90020,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了50%)]],weight = 100,},
								[14] = {id = 14,type = 2,buff = 90021,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了40%)]],weight = 100,},
								[15] = {id = 15,type = 2,buff = 90022,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了30%)]],weight = 100,},
								[16] = {id = 16,type = 2,buff = 90023,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了20%)]],weight = 100,},
								[17] = {id = 17,type = 2,buff = 90024,scene = [[]],Position = [[]],textbox = [[急忙赶路，踩到了狗屎！(10秒内速度降低了10%)]],weight = 100,},
								[18] = {id = 18,type = 2,buff = 90025,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升80%)]],weight = 100,},
								[19] = {id = 19,type = 2,buff = 90026,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升70%)]],weight = 100,},
								[20] = {id = 20,type = 2,buff = 90027,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升60%)]],weight = 100,},
								[21] = {id = 21,type = 2,buff = 90028,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升50%)]],weight = 100,},
								[22] = {id = 22,type = 2,buff = 90029,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升40%)]],weight = 100,},
								[23] = {id = 23,type = 2,buff = 90030,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升30%)]],weight = 100,},
								[24] = {id = 24,type = 2,buff = 90031,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升20%)]],weight = 100,},
								[25] = {id = 25,type = 2,buff = 90032,scene = [[]],Position = [[]],textbox = [[路途遥远，你加快了步伐（30秒内速度提升10%)]],weight = 100,},
								[26] = {id = 26,type = 2,buff = 90033,scene = [[]],Position = [[]],textbox = [[你被淘气的高人施了法术，无法动弹了（定身15秒）]],weight = 100,},
								[27] = {id = 27,type = 2,buff = 90034,scene = [[]],Position = [[]],textbox = [[突遇暴雨，你找了个地方避雨（定身10秒）]],weight = 100,},
								[28] = {id = 28,type = 2,buff = 90035,scene = [[]],Position = [[]],textbox = [[你急忙赶路，一脚踏进了泥潭（定身5秒）]],weight = 100,},
								[29] = {id = 29,type = 3,buff = [[]],scene = [[]],Position = [[]],textbox = [[你遇到了仙人指路，一眨眼到达了目标地图]],weight = 500,},
								[30] = {id = 30,type = 4,buff = [[]],scene = 6006,Position = [[106,9]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[31] = {id = 31,type = 4,buff = [[]],scene = 6006,Position = [[77,102]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[32] = {id = 32,type = 4,buff = [[]],scene = 6006,Position = [[49,51]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[33] = {id = 33,type = 4,buff = [[]],scene = 6007,Position = [[112,104]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[34] = {id = 34,type = 4,buff = [[]],scene = 6007,Position = [[68,12]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[35] = {id = 35,type = 4,buff = [[]],scene = 6007,Position = [[63,165]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
								[36] = {id = 36,type = 4,buff = [[]],scene = 6008,Position = [[191,380]],textbox = [[眼前一黑，竟然来到了一处未知的地方(可使用随身商店中的回城符回到夏都城）]],weight = 100,},
							},
						},
					},
					balance = {
						[1] = {keeptime = 10,
							event = {
								[1] = {id = 1,type = 1,weight = 7000,reward = 1,rewardnum = 1,word = [[]],npcName = [[]],halfBody = [[]],textbox = [[你发现了一个宝箱，乘四下无人，立刻将宝物收到了包里]],},
								[2] = {id = 2,type = 1,weight = 3000,reward = 2,rewardnum = 1,word = [[]],npcName = [[]],halfBody = [[]],textbox = [[你发现了一个宝箱，乘四下无人，立刻将宝物收到了包里]],},
								[3] = {id = 3,type = 3,weight = 3500,reward = 1,rewardnum = 1,word = [[]],npcName = [[宝箱守护者]],halfBody = 123,textbox = [[]],},
								[4] = {id = 4,type = 3,weight = 1500,reward = 2,rewardnum = 1,word = [[]],npcName = [[宝箱守护者]],halfBody = 143,textbox = [[]],},
								[5] = {id = 5,type = 4,weight = 700,reward = 1,rewardnum = 1,word = [[]],npcName = [[]],halfBody = [[]],textbox = [[你挖到了个箱子，打开箱子后眼前一黑，被宝箱中的精灵传送到了个奇怪的地方，快回去找它]],},
								[6] = {id = 6,type = 4,weight = 300,reward = 2,rewardnum = 1,word = [[]],npcName = [[]],halfBody = [[]],textbox = [[你挖到了个箱子，打开箱子后眼前一黑，被宝箱中的精灵传送到了个奇怪的地方，快回去找它]],},
								[7] = {id = 7,type = 2,weight = 3000,reward = [[]],rewardnum = [[]],word = [[你打开了宝箱，宝箱中封印的怪物立刻飞向夏族各地]],npcName = [[魔物]],halfBody = 137,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 4,text = [[前往铲除（立即飞到怪物地点）]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你搜刮了一些怪物遗留的宝物]],reward = 2,rewardnum = 1,},
										[2] = {id = 2,brancetype = 7,text = [[假装看不见]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[怪物消散了，宝箱中的宝物也消失了]],reward = 0,rewardnum = [[]],},
									},
								},
								[8] = {id = 8,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[想不到你竟然能找到我，只要你找到我要的，我就能帮你炼化出宝物哦]],npcName = [[宝物精灵]],halfBody = 188,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 3,text = [[给他10万银两]],needmoney = 100000,needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[神奇的精灵帮你炼化出一个宝物后离开了]],reward = 2,rewardnum = 1,},
										[2] = {id = 2,brancetype = 3,text = [[给他100万银两]],needmoney = 1000000,needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[神奇的精灵帮你炼化出一个宝物后离开了]],reward = 2,rewardnum = 1,},
										[3] = {id = 3,brancetype = 2,text = [[给他10元宝]],needmoney = [[]],needemoney = 10,needitem = [[]],neednum = [[]],textbox = [[神奇的精灵帮你炼化出一个宝物后离开了]],reward = 2,rewardnum = 2,},
										[4] = {id = 4,brancetype = 7,text = [[无视他]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[]],reward = 0,rewardnum = [[]],},
									},
								},
								[9] = {id = 9,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[少侠能给我一个1级生命灵药吗(可以从随身商店购买）]],npcName = [[土著女孩]],halfBody = 145,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 1,text = [[给她]],needmoney = [[]],needemoney = [[]],needitem = 100001,neednum = 1,textbox = [[谢谢大侠倾囊相送]],reward = 1,rewardnum = 1,},
										[2] = {id = 2,brancetype = 3,text = [[点此购买后给她，需要10两银子]],needmoney = 10,needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[谢谢大侠倾囊相送]],reward = 1,rewardnum = 1,},
										[3] = {id = 3,brancetype = 7,text = [[无视她]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[女孩转身走开了（任务结束）]],reward = 0,rewardnum = [[]],},
									},
								},
								[10] = {id = 10,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[少侠能给我一个初级强化石吗（可以从各类活动、商城中获得）]],npcName = [[土著女孩]],halfBody = 145,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 1,text = [[给她]],needmoney = [[]],needemoney = [[]],needitem = 105001,neednum = 1,textbox = [[谢谢大侠倾囊相送]],reward = 2,rewardnum = 1,},
										[2] = {id = 2,brancetype = 2,text = [[点此购买后给她，需要5元宝]],needmoney = [[]],needemoney = 5,needitem = [[]],neednum = [[]],textbox = [[谢谢大侠倾囊相送]],reward = 2,rewardnum = 1,},
										[3] = {id = 3,brancetype = 7,text = [[无视她]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[女孩转身走开了（任务结束）]],reward = 0,rewardnum = [[]],},
									},
								},
								[11] = {id = 11,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[少侠能给我一个护送令吗（可以从商城中购买）]],npcName = [[土著女孩]],halfBody = 145,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 1,text = [[给她]],needmoney = [[]],needemoney = [[]],needitem = 600018,neednum = 1,textbox = [[谢谢大侠倾囊相送]],reward = 2,rewardnum = 1,},
										[2] = {id = 2,brancetype = 2,text = [[点此购买后给她，需要10元宝]],needmoney = [[]],needemoney = 10,needitem = [[]],neednum = [[]],textbox = [[谢谢大侠倾囊相送]],reward = 2,rewardnum = 1,},
										[3] = {id = 3,brancetype = 7,text = [[无视他]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[女孩转身走开了（任务结束）]],reward = 0,rewardnum = [[]],},
									},
								},
								[12] = {id = 12,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[领主你觉得我美吗，快给我送花，啦啦啦]],npcName = [[貌美如花]],halfBody = 134,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 1,text = [[给她1朵红玫瑰]],needmoney = [[]],needemoney = [[]],needitem = 610000,neednum = 1,textbox = [[小主真是有眼光，这些礼物还请收下]],reward = 1,rewardnum = 1,},
										[2] = {id = 2,brancetype = 1,text = [[给她9朵红玫瑰]],needmoney = [[]],needemoney = [[]],needitem = 610001,neednum = 1,textbox = [[小主真是有眼光，这些礼物还请收下]],reward = 2,rewardnum = 2,},
										[3] = {id = 3,brancetype = 1,text = [[给她99朵红玫瑰]],needmoney = [[]],needemoney = [[]],needitem = 610002,neednum = 1,textbox = [[小主真是有眼光，这些礼物还请收下]],reward = 2,rewardnum = 3,},
										[4] = {id = 4,brancetype = 7,text = [[吓死我了，赶紧跑]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[]],reward = 0,rewardnum = [[]],},
									},
								},
								[13] = {id = 13,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[你挖到了一个大宝箱]],npcName = [[宝藏]],halfBody = 100,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 7,text = [[打开宝藏]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[]],reward = 2,rewardnum = 3,},
									},
								},
								[14] = {id = 14,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[你发现了两个宝箱，宝箱内传出了一股声音：你只能选择其中一个打开]],npcName = [[宝藏守护兽]],halfBody = 188,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 7,text = [[打开左边宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你得到了宝藏]],reward = 1,rewardnum = 1,},
										[2] = {id = 2,brancetype = 7,text = [[打开右边宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你得到了宝藏]],reward = 2,rewardnum = 1,},
										[3] = {id = 2,brancetype = 7,text = [[同时打开2个宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你无视劝告夺走了所有宝物]],reward = 2,rewardnum = 2,},
									},
								},
								[15] = {id = 15,type = 2,weight = 200,reward = [[]],rewardnum = [[]],word = [[你发现了两个宝箱，宝箱内传出了一股声音：你只能选择其中一个打开]],npcName = [[宝藏守护兽]],halfBody = 188,textbox = [[]],
									brance = {
										[1] = {id = 1,brancetype = 7,text = [[打开左边宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你得到了宝藏]],reward = 2,rewardnum = 1,},
										[2] = {id = 2,brancetype = 7,text = [[打开右边宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你得到了宝藏]],reward = 1,rewardnum = 1,},
										[3] = {id = 2,brancetype = 7,text = [[同时打开2个宝箱]],needmoney = [[]],needemoney = [[]],needitem = [[]],neednum = [[]],textbox = [[你太贪婪了(2个宝箱在打开的瞬间爆炸了）]],reward = 0,rewardnum = [[]],},
									},
								},
							},
						},
					},
					reward = {
						[1] = {reward1 = [[105002,105202,600092,600068,600002]],
							jackpot = {
								[1] = {reward = 0,},
								[2] = {reward = 1,
									info = {
										[1] = {id = 1,itemid = 105002,num = 2,weight = 8,record = 0,},
										[2] = {id = 2,itemid = 105002,num = 3,weight = 4,record = 0,},
										[3] = {id = 3,itemid = 105201,num = 1,weight = 8,record = 0,},
										[4] = {id = 4,itemid = 105201,num = 2,weight = 4,record = 0,},
										[5] = {id = 5,itemid = 108961,num = 1,weight = 4,record = 0,},
										[6] = {id = 6,itemid = 108960,num = 1,weight = 8,record = 0,},
										[7] = {id = 7,itemid = 950010,num = 1,weight = 4,record = 0,},
										[8] = {id = 8,itemid = 108306,num = 2,weight = 7,record = 0,},
										[9] = {id = 9,itemid = 600092,num = 3,weight = 7,record = 0,},
										[10] = {id = 10,itemid = 190003,num = 1,weight = 7,record = 0,},
										[11] = {id = 11,itemid = 999997,num = 20,weight = 7,record = 0,},
										[12] = {id = 12,itemid = 100583,num = 3,weight = 5,record = 0,},
										[13] = {id = 13,itemid = 600018,num = 3,weight = 5,record = 0,},
										[14] = {id = 14,itemid = 105301,num = 6,weight = 5,record = 0,},
										[15] = {id = 15,itemid = 105401,num = 3,weight = 5,record = 0,},
										[16] = {id = 16,itemid = 160014,num = 1,weight = 8,record = 0,},
										[17] = {id = 17,itemid = 160015,num = 1,weight = 4,record = 0,},
									},
								},
								[3] = {reward = 2,
									info = {
										[1] = {id = 1,itemid = 105002,num = 3,weight = 7,record = 0,},
										[2] = {id = 2,itemid = 105002,num = 5,weight = 4,record = 0,},
										[3] = {id = 3,itemid = 105201,num = 2,weight = 7,record = 0,},
										[4] = {id = 4,itemid = 105201,num = 3,weight = 4,record = 0,},
										[5] = {id = 5,itemid = 108962,num = 1,weight = 4,record = 0,},
										[6] = {id = 6,itemid = 108961,num = 1,weight = 7,record = 0,},
										[7] = {id = 7,itemid = 950010,num = 1,weight = 4,record = 0,},
										[8] = {id = 8,itemid = 108306,num = 4,weight = 6,record = 0,},
										[9] = {id = 9,itemid = 600092,num = 4,weight = 7,record = 0,},
										[10] = {id = 10,itemid = 190002,num = 8,weight = 7,record = 0,},
										[11] = {id = 11,itemid = 999997,num = 30,weight = 7,record = 0,},
										[12] = {id = 12,itemid = 100583,num = 4,weight = 5,record = 0,},
										[13] = {id = 13,itemid = 600018,num = 5,weight = 5,record = 0,},
										[14] = {id = 14,itemid = 105301,num = 8,weight = 5,record = 0,},
										[15] = {id = 15,itemid = 105401,num = 4,weight = 5,record = 0,},
										[16] = {id = 16,itemid = 160015,num = 1,weight = 8,record = 0,},
										[17] = {id = 17,itemid = 160016,num = 1,weight = 5,record = 0,},
										[18] = {id = 18,itemid = 160017,num = 1,weight = 3,record = 0,},
									},
								},
							},
						},
					},
					fb = {
						[1] = {fbId = 1,name = [[寻宝副本]],mapId = 8005,startPosition = [[77,51]],revivePos = [[77,51]],holdTime = 300,waitTime = 10,instruction = [[这个是右侧TIP副本介绍！]],
							mon = {
								[1] = {monsterId = 910001,monsterDirection = 1,position = [[91,30]],},
							},
						},
					},
					question = {
						[1] = {id = 1,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:雪鹰领主是谁的作品？]],answer_1 = [[我吃西红柿]],answer_2 = [[天蚕土豆]],answer_3 = [[唐家三少]],answer_4 = [[辰东]],key = 1,},
						[2] = {id = 2,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的家乡是哪里？]],answer_1 = [[仪水县]],answer_2 = [[溪平县]],answer_3 = [[封昌县]],answer_4 = [[横安县]],key = 1,},
						[3] = {id = 3,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的父亲是？]],answer_1 = [[东伯烈]],answer_2 = [[东伯雄]],answer_3 = [[东伯列]],answer_4 = [[东伯日]],key = 1,},
						[4] = {id = 4,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的母亲是？]],answer_1 = [[墨阳瑜]],answer_2 = [[墨阳琛]],answer_3 = [[墨阳琦]],answer_4 = [[墨阳辰白]],key = 1,},
						[5] = {id = 5,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的弟弟是？]],answer_1 = [[东伯青石]],answer_2 = [[东伯纳兰]],answer_3 = [[东伯雪石]],answer_4 = [[东伯雪云]],key = 1,},
						[6] = {id = 6,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:龙山帝国的开创者是谁？]],answer_1 = [[龙山大帝]],answer_2 = [[赤云大帝]],answer_3 = [[紫雷帝君]],answer_4 = [[天风大帝]],key = 1,},
						[7] = {id = 7,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在府城之战中获得了第几名？]],answer_1 = [[第一名]],answer_2 = [[第二名]],answer_3 = [[第三名]],answer_4 = [[第四名]],key = 1,},
						[8] = {id = 8,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在哪里得到了银月狼王之心？]],answer_1 = [[毁灭山脉]],answer_2 = [[黑风渊]],answer_3 = [[黑风崖]],answer_4 = [[清河郡]],key = 1,},
						[9] = {id = 9,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯烈是什么境界的修为？]],answer_1 = [[天阶骑士]],answer_2 = [[人阶骑士]],answer_3 = [[流星骑士]],answer_4 = [[超凡骑士]],key = 1,},
						[10] = {id = 10,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰修炼的第一本枪法是？]],answer_1 = [[《心意枪法》]],answer_2 = [[《玄冰枪法》]],answer_3 = [[《血雨枪法》]],answer_4 = [[《飘雪枪法》]],key = 1,},
						[11] = {id = 11,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的第一把神兵是？]],answer_1 = [[飞雪神枪]],answer_2 = [[紫血枪]],answer_3 = [[星石火云枪]],answer_4 = [[黑龙枪]],key = 1,},
						[12] = {id = 12,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰修炼的第一本斗气法门是？]],answer_1 = [[《火焰三段法》]],answer_2 = [[《魔龙力》]],answer_3 = [[《天水注》]],answer_4 = [[《光芒琉璃身》]],key = 1,},
						[13] = {id = 13,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:长风学院院长是谁？]],answer_1 = [[池丘白]],answer_2 = [[彭山]],answer_3 = [[司空阳]],answer_4 = [[太叔宫主]],key = 1,},
						[14] = {id = 14,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰用来测试弟弟法力的物品是什么？]],answer_1 = [[水晶球]],answer_2 = [[水晶矿石]],answer_3 = [[水晶柱]],answer_4 = [[水晶石台]],key = 1,},
						[15] = {id = 15,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的第一匹坐骑是？]],answer_1 = [[飞霜魔兽马驹]],answer_2 = [[雪原白毛象]],answer_3 = [[银月狼王]],answer_4 = [[飞天蜈蚣]],key = 1,},
						[16] = {id = 16,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰觉醒的血脉是？]],answer_1 = [[力量翻倍]],answer_2 = [[巨斧血脉]],answer_3 = [[闪电血脉]],answer_4 = [[不死血脉]],key = 1,},
						[17] = {id = 17,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:仪水城最大的兵器铺名字是？]],answer_1 = [[旭明杂货铺]],answer_2 = [[凤舞坊]],answer_3 = [[飞凤斋]],answer_4 = [[天仙楼]],key = 1,},
						[18] = {id = 18,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:白源之大法师要什么东西作为青石的拜师礼？]],answer_1 = [[狼王之心]],answer_2 = [[熊王之心]],answer_3 = [[狮王之心]],answer_4 = [[虎王之心]],key = 1,},
						[19] = {id = 19,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:弯刀盟的老巢在哪里？]],answer_1 = [[毁灭山脉]],answer_2 = [[黑风崖]],answer_3 = [[黑风神宫]],answer_4 = [[清河郡]],key = 1,},
						[20] = {id = 20,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰第一次跟谁一起去的毁灭山脉？]],answer_1 = [[宗凌]],answer_2 = [[铜三]],answer_3 = [[余靖秋]],answer_4 = [[青石]],key = 1,},
						[21] = {id = 21,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:玄冰枪法是谁创造的？]],answer_1 = [[谷元寒]],answer_2 = [[池丘白]],answer_3 = [[东伯列]],answer_4 = [[薪火宫宫主]],key = 1,},
						[22] = {id = 22,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:弯刀盟盟主是谁？]],answer_1 = [[弯刀盖斌]],answer_2 = [[项庞云]],answer_3 = [[卢怀如]],answer_4 = [[尤兰领主]],key = 1,},
						[23] = {id = 23,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:哪个超凡家族将雪鹰的双亲抓走的？]],answer_1 = [[墨阳家族]],answer_2 = [[慕容家族]],answer_3 = [[太叔家族]],answer_4 = [[公孙家族]],key = 1,},
						[24] = {id = 24,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:墨阳家族的东稥湖的炼金大法师是谁？]],answer_1 = [[许光清]],answer_2 = [[白源之]],answer_3 = [[墨阳琛]],answer_4 = [[宗凌]],key = 1,},
						[25] = {id = 25,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:踏雪魔兽马驹是几阶魔兽？]],answer_1 = [[三阶]],answer_2 = [[二阶]],answer_3 = [[一阶]],answer_4 = [[四阶]],key = 1,},
						[26] = {id = 26,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:卢怀如用来刺激手下潜能的丹药是？]],answer_1 = [[魔神水石]],answer_2 = [[海洋界石]],answer_3 = [[魔灵谷草]],answer_4 = [[朱果]],key = 1,},
						[27] = {id = 27,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:青石的第一个女朋友是？]],answer_1 = [[姬容]],answer_2 = [[孔悠月]],answer_3 = [[程灵淑]],answer_4 = [[卓依]],key = 1,},
						[28] = {id = 28,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:青石在仪水城郊外误杀的青年是？]],answer_1 = [[崔琥]],answer_2 = [[崔金鹏]],answer_3 = [[项庞云]],answer_4 = [[仇凡]],key = 1,},
						[29] = {id = 29,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:龙山帝国最可怕的杀手组织是？]],answer_1 = [[血刃酒馆]],answer_2 = [[龙山楼]],answer_3 = [[血刃神庭]],answer_4 = [[黑白神山]],key = 1,},
						[30] = {id = 30,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面几个哪位是项庞云的手下？]],answer_1 = [[风魔]],answer_2 = [[铜三]],answer_3 = [[宗凌]],answer_4 = [[盖斌]],key = 1,},
						[31] = {id = 31,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:项庞云是什么级别的高手？]],answer_1 = [[称号级]],answer_2 = [[银月级]],answer_3 = [[超凡级]],answer_4 = [[半神级]],key = 1,},
						[32] = {id = 32,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:孔悠月是谁的初恋？]],answer_1 = [[东伯雪鹰]],answer_2 = [[东伯青石]],answer_3 = [[铜三]],answer_4 = [[宗凌]],key = 1,},
						[33] = {id = 33,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:项庞云是龙山榜排名多少的高手？]],answer_1 = 525,answer_2 = 524,answer_3 = 523,answer_4 = 522,key = 1,},
						[34] = {id = 34,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:项庞云是在哪里被东伯雪鹰杀死的？]],answer_1 = [[黑风崖]],answer_2 = [[毁灭山脉]],answer_3 = [[清河郡]],answer_4 = [[墨阳家族]],key = 1,},
						[35] = {id = 35,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:黑风神宫是谁的府邸？]],answer_1 = [[黑风老祖]],answer_2 = [[雷真]],answer_3 = [[晁青]],answer_4 = [[宫愚]],key = 1,},
						[36] = {id = 36,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:黑风神宫的守卫是什么种族？]],answer_1 = [[炼金生物]],answer_2 = [[恶魔]],answer_3 = [[土著]],answer_4 = [[魔兽]],key = 1,},
						[37] = {id = 37,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的母亲被关押在哪里？]],answer_1 = [[雷潮涯]],answer_2 = [[东稥湖]],answer_3 = [[墨家古宅]],answer_4 = [[清河郡]],key = 1,},
						[38] = {id = 38,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:海洋界石灵液有什么作用？]],answer_1 = [[升级伙伴]],answer_2 = [[补充灵力]],answer_3 = [[浇灌灵药]],answer_4 = [[刺激潜能]],key = 1,},
						[39] = {id = 39,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰之前的圣榜第一是谁？]],answer_1 = [[池丘白]],answer_2 = [[贝鲁领主]],answer_3 = [[血魔神]],answer_4 = [[涂亮]],key = 1,},
						[40] = {id = 40,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰之前的半神榜第一是谁？ ]],answer_1 = [[贺源]],answer_2 = [[火魔大帝]],answer_3 = [[奥兰]],answer_4 = [[晁青]],key = 1,},
						[41] = {id = 41,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个势力不属于夏族六大超凡组织？]],answer_1 = [[巫神殿]],answer_2 = [[血刃酒馆]],answer_3 = [[黑白神山]],answer_4 = [[云雾城]],key = 1,},
						[42] = {id = 42,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰最终选择了加入下面哪一方超凡组织？]],answer_1 = [[水源道观]],answer_2 = [[黑白神山]],answer_3 = [[海神宫]],answer_4 = [[云雾城]],key = 1,},
						[43] = {id = 43,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:水源道观副观主是谁？]],answer_1 = [[晁青]],answer_2 = [[贺源]],answer_3 = [[司空阳]],answer_4 = [[宫愚]],key = 1,},
						[44] = {id = 44,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:夏族真正意义上的都城是哪一个？]],answer_1 = [[夏都城]],answer_2 = [[夏皇城]],answer_3 = [[薪火宫]],answer_4 = [[云雾城]],key = 1,},
						[45] = {id = 45,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡生死战胜了多少场？]],answer_1 = [[9场]],answer_2 = [[8场]],answer_3 = [[7场]],answer_4 = [[10场]],key = 1,},
						[46] = {id = 46,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在生死殿中用什么绝技打败了金光魔孔雀？]],answer_1 = [[水火蛟龙杀]],answer_2 = [[星辰陨灭击]],answer_3 = [[大混洞真力]],answer_4 = [[万劫混元身]],key = 1,},
						[47] = {id = 47,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:百战密室中有多少个炼金生物？]],answer_1 = 100,answer_2 = 101,answer_3 = 102,answer_4 = 99,key = 1,},
						[48] = {id = 48,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:真意共分为几品？]],answer_1 = [[九品]],answer_2 = [[七品]],answer_3 = [[八品]],answer_4 = [[六品]],key = 1,},
						[49] = {id = 49,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在哪里认识的卓依？]],answer_1 = [[赤云山]],answer_2 = [[黑白神山]],answer_3 = [[薪火宫]],answer_4 = [[水源道观]],key = 1,},
						[50] = {id = 50,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰因为领悟什么奥妙引得司空阳震怒？]],answer_1 = [[风之奥秘]],answer_2 = [[雷之奥妙]],answer_3 = [[水之奥妙]],answer_4 = [[火之奥妙]],key = 1,},
						[51] = {id = 51,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下列哪位不是神界最顶尖的存在？]],answer_1 = [[庞依]],answer_2 = [[血刃神帝]],answer_3 = [[时空岛主]],answer_4 = [[万神殿主]],key = 1,},
						[52] = {id = 52,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:余靖秋灵魂受伤之后是谁将她救好的？]],answer_1 = [[赤火老祖]],answer_2 = [[血刃神帝]],answer_3 = [[时空岛主]],answer_4 = [[万神殿主]],key = 1,},
						[53] = {id = 53,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:红尘圣主的至交好友是谁？]],answer_1 = [[赤火老祖]],answer_2 = [[血刃神帝]],answer_3 = [[时空岛主]],answer_4 = [[万神殿主]],key = 1,},
						[54] = {id = 54,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:万花宴是由以下哪个势力主办的？]],answer_1 = [[血刃神廷]],answer_2 = [[时空神殿]],answer_3 = [[万神殿]],answer_4 = [[赤云山]],key = 1,},
						[55] = {id = 55,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:万花宴多久举办一次？]],answer_1 = [[一千万年]],answer_2 = [[一百万年]],answer_3 = [[一万年]],answer_4 = [[一千年]],key = 1,},
						[56] = {id = 56,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:成为四重天界神需要掌握几种一品神心？]],answer_1 = [[四种]],answer_2 = [[三种]],answer_3 = [[二中]],answer_4 = [[一种]],key = 1,},
						[57] = {id = 57,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:夏族的第一位界神是谁?]],answer_1 = [[东伯雪鹰]],answer_2 = [[晁青]],answer_3 = [[贺源]],answer_4 = [[余靖秋]],key = 1,},
						[58] = {id = 58,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪个不是东伯雪鹰的五影之一？]],answer_1 = [[黑铁]],answer_2 = [[圣童]],answer_3 = [[战将]],answer_4 = [[刀客]],key = 1,},
						[59] = {id = 59,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的第一个儿子叫什么名字？]],answer_1 = [[东伯玉]],answer_2 = [[东伯青瑶]],answer_3 = [[东伯青石]],answer_4 = [[东伯晴]],key = 1,},
						[60] = {id = 60,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:以下人物哪位是天剑宗的长老？]],answer_1 = [[云海大帝]],answer_2 = [[东伯雪鹰]],answer_3 = [[晁青]],answer_4 = [[贺源]],key = 1,},
						[61] = {id = 61,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:血刃神廷治下一共有多少府？]],answer_1 = [[十九府]],answer_2 = [[十八府]],answer_3 = [[十七府]],answer_4 = [[十六府]],key = 1,},
						[62] = {id = 62,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在神界去的第一个府是什么府？]],answer_1 = [[安海府]],answer_2 = [[东阳府]],answer_3 = [[北海府]],answer_4 = [[西云府]],key = 1,},
						[63] = {id = 63,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:云海大帝被关押在下面哪颗星球上？]],answer_1 = [[冰铁星]],answer_2 = [[冰雪星]],answer_3 = [[寒霜星]],answer_4 = [[烈火星]],key = 1,},
						[64] = {id = 64,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:神界流通的货币是什么？]],answer_1 = [[神晶]],answer_2 = [[源石]],answer_3 = [[星石]],answer_4 = [[铁矿]],key = 1,},
						[65] = {id = 65,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:云海大帝是被下面哪一方势力抓走的?]],answer_1 = [[黑骨山]],answer_2 = [[时空神殿]],answer_3 = [[万神殿]],answer_4 = [[赤云山]],key = 1,},
						[66] = {id = 66,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:是谁独闯冰铁星矿物星球救出了云海大帝?]],answer_1 = [[东伯雪鹰]],answer_2 = [[余靖秋]],answer_3 = [[晁青]],answer_4 = [[紫雷帝君]],key = 1,},
						[67] = {id = 67,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:冰铁星内沉睡的高手本体是什么？]],answer_1 = [[黄金老鼠]],answer_2 = [[黄金狮子]],answer_3 = [[黄金狼]],answer_4 = [[黄金巨象]],key = 1,},
						[68] = {id = 68,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在神界落脚的第一个城池叫什么名字？]],answer_1 = [[白沙城]],answer_2 = [[吴山城]],answer_3 = [[铁山城]],answer_4 = [[ 仪水城]],key = 1,},
						[69] = {id = 69,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:飞云湖少主是下列人物中的哪一个？]],answer_1 = [[金梅阳]],answer_2 = [[童亚]],answer_3 = [[万风]],answer_4 = [[苍秋]],key = 1,},
						[70] = {id = 70,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:公良远是什么级别的高手？]],answer_1 = [[圣级]],answer_2 = [[称号级]],answer_3 = [[半神级]],answer_4 = [[流星级]],key = 1,},
						[71] = {id = 71,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡生死战中第四场的对手是谁？]],answer_1 = [[公良远]],answer_2 = [[余靖秋]],answer_3 = [[晁青]],answer_4 = [[紫雷帝君]],key = 1,},
						[72] = {id = 72,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在水源道观选择了什么秘术？]],answer_1 = [[《魔龙功》]],answer_2 = [[《万劫混元身》]],answer_3 = [[《大混洞真力》]],answer_4 = [[《太皓》]],key = 1,},
						[73] = {id = 73,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:超凡生死战获胜的条件是什么？]],answer_1 = [[击败对方]],answer_2 = [[杀死对方]],answer_3 = [[连胜两场]],answer_4 = [[连胜一场]],key = 1,},
						[74] = {id = 74,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:公良远长老的绝技是什么?]],answer_1 = [[截风十五剑]],answer_2 = [[太虚剑法]],answer_3 = [[万劫混元身]],answer_4 = [[大混洞真力]],key = 1,},
						[75] = {id = 75,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡生死战中挡住了公良远多少剑？]],answer_1 = [[六剑]],answer_2 = [[五剑]],answer_3 = [[四剑]],answer_4 = [[三剑]],key = 1,},
						[76] = {id = 76,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰参加超凡生死战的时候是万物镜第几境界？]],answer_1 = [[第一]],answer_2 = [[第二]],answer_3 = [[第三]],answer_4 = [[第四]],key = 1,},
						[77] = {id = 77,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第五战的对手是谁？]],answer_1 = [[土著巨汉]],answer_2 = [[金光魔孔雀]],answer_3 = [[公良远]],answer_4 = [[炼金蜥蜴]],key = 1,},
						[78] = {id = 78,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第一战的对手是谁？]],answer_1 = [[炼金蜥蜴]],answer_2 = [[土著巨汉]],answer_3 = [[金光魔孔雀]],answer_4 = [[公良远]],key = 1,},
						[79] = {id = 79,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第二战的对手是]],answer_1 = [[炼金蝎子]],answer_2 = [[土著巨汉]],answer_3 = [[金光魔孔雀]],answer_4 = [[公良远]],key = 1,},
						[80] = {id = 80,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第三战的对手是谁？]],answer_1 = [[土著超凡]],answer_2 = [[金光魔孔雀]],answer_3 = [[公良远]],answer_4 = [[炼金蝎子]],key = 1,},
						[81] = {id = 81,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第六战的对手是谁？]],answer_1 = [[中等超凡土著]],answer_2 = [[金光魔孔雀]],answer_3 = [[公良远]],answer_4 = [[炼金蝎子]],key = 1,},
						[82] = {id = 82,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第七战的对手是谁？]],answer_1 = [[黑色猿猴]],answer_2 = [[金光魔孔雀]],answer_3 = [[土著巨汉]],answer_4 = [[公良远]],key = 1,},
						[83] = {id = 83,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第九战的对手是谁？]],answer_1 = [[深渊恶魔]],answer_2 = [[土著巨汉]],answer_3 = [[公良远]],answer_4 = [[炼金蝎子]],key = 1,},
						[84] = {id = 84,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰超凡生死战第八战的对手是谁？]],answer_1 = [[金光魔孔雀]],answer_2 = [[土著巨汉]],answer_3 = [[公良远]],answer_4 = [[炼金蝎子]],key = 1,},
						[85] = {id = 85,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡生死战第六场凭什么战胜了对手？]],answer_1 = [[太古血脉]],answer_2 = [[魔龙力]],answer_3 = [[水火蛟龙杀]],answer_4 = [[大混洞真力]],key = 1,},
						[86] = {id = 86,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡生死战中将哪两种真意融合了？]],answer_1 = [[水火]],answer_2 = [[金木]],answer_3 = [[水土]],answer_4 = [[火土]],key = 1,},
						[87] = {id = 87,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:阴阳真意是几品真意？]],answer_1 = [[二品]],answer_2 = [[一品]],answer_3 = [[三品]],answer_4 = [[四品]],key = 1,},
						[88] = {id = 88,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:世界真意是几品真意?]],answer_1 = [[一品]],answer_2 = [[二品]],answer_3 = [[三品]],answer_4 = [[四品]],key = 1,},
						[89] = {id = 89,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:空间切割是几品真意？]],answer_1 = [[三品]],answer_2 = [[二品]],answer_3 = [[一品]],answer_4 = [[四品]],key = 1,},
						[90] = {id = 90,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:不死真意是几品真意？]],answer_1 = [[四品]],answer_2 = [[一品]],answer_3 = [[二品]],answer_4 = [[三品]],key = 1,},
						[91] = {id = 91,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:光明真意是几品真意？]],answer_1 = [[五品]],answer_2 = [[二品]],answer_3 = [[三品]],answer_4 = [[四品]],key = 1,},
						[92] = {id = 92,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:水之真意是几品真意？]],answer_1 = [[六品]],answer_2 = [[二品]],answer_3 = [[三品]],answer_4 = [[四品]],key = 1,},
						[93] = {id = 93,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:大山真意是几品真意？]],answer_1 = [[七品]],answer_2 = [[六品]],answer_3 = [[三品]],answer_4 = [[四品]],key = 1,},
						[94] = {id = 94,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:柔水真意是几品真意？]],answer_1 = [[八品]],answer_2 = [[七品]],answer_3 = [[六品]],answer_4 = [[四品]],key = 1,},
						[95] = {id = 95,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:飞火真意是几品真意？]],answer_1 = [[九品]],answer_2 = [[八品]],answer_3 = [[七品]],answer_4 = [[五品]],key = 1,},
						[96] = {id = 96,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:是谁开启了元老会表决提议东伯雪鹰为候补元老？]],answer_1 = [[晁青]],answer_2 = [[余靖秋]],answer_3 = [[贺源]],answer_4 = [[紫雷帝君]],key = 1,},
						[97] = {id = 97,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:水火真意是几品真意？]],answer_1 = [[四品]],answer_2 = [[五品]],answer_3 = [[三品]],answer_4 = [[六品]],key = 1,},
						[98] = {id = 98,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪个人物是东伯雪鹰的女管家？]],answer_1 = [[许琴]],answer_2 = [[余靖秋]],answer_3 = [[贺源]],answer_4 = [[紫雷帝君]],key = 1,},
						[99] = {id = 99,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:飞天级超凡的生命是多久？]],answer_1 = [[800年]],answer_2 = [[900年]],answer_3 = [[1000年]],answer_4 = [[1200年]],key = 1,},
						[100] = {id = 100,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:圣级超凡的生命是多久？]],answer_1 = [[1500年]],answer_2 = [[900年]],answer_3 = [[1000年]],answer_4 = [[1200年]],key = 1,},
						[101] = {id = 101,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:半神超凡的生命是多久？]],answer_1 = [[3000年]],answer_2 = [[1500年]],answer_3 = [[900年]],answer_4 = [[1000年]],key = 1,},
						[102] = {id = 102,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在薪火世界遇到的第一个半神是谁？]],answer_1 = [[宫愚]],answer_2 = [[贺源]],answer_3 = [[晁青]],answer_4 = [[陈宫主]],key = 1,},
						[103] = {id = 103,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:薪火宫的镇族神器是谁送的？]],answer_1 = [[赤云大帝]],answer_2 = [[紫雷帝君]],answer_3 = [[云海帝君]],answer_4 = [[东伯帝君]],key = 1,},
						[104] = {id = 104,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:司徒鸿掌握的是什么奥妙？]],answer_1 = [[空间奥妙]],answer_2 = [[生命奥妙]],answer_3 = [[死亡奥妙]],answer_4 = [[时间奥妙]],key = 1,},
						[105] = {id = 105,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:都柔柔掌握的是什么奥妙？]],answer_1 = [[时间奥妙]],answer_2 = [[空间奥妙]],answer_3 = [[生命奥妙]],answer_4 = [[死亡奥妙]],key = 1,},
						[106] = {id = 106,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:文永安掌握的是什么奥妙？]],answer_1 = [[生命奥妙]],answer_2 = [[时间奥妙]],answer_3 = [[空间奥妙]],answer_4 = [[死亡奥妙]],key = 1,},
						[107] = {id = 107,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:卓师姐掌握的是什么奥妙？]],answer_1 = [[太阴奥妙]],answer_2 = [[时间奥妙]],answer_3 = [[空间奥妙]],answer_4 = [[死亡奥妙]],key = 1,},
						[108] = {id = 108,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一位师傅不是赤云山的血肉战兵？]],answer_1 = [[烈火神将]],answer_2 = [[刀师父]],answer_3 = [[盾师父]],answer_4 = [[枪师父]],key = 1,},
						[109] = {id = 109,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:张鹏的绝技是什么？]],answer_1 = [[空间刃]],answer_2 = [[大混洞真力]],answer_3 = [[阴影空间]],answer_4 = [[空间切割]],key = 1,},
						[110] = {id = 110,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:薪火宫放置夏族历史书籍的地方叫什么？]],answer_1 = [[夏史阁]],answer_2 = [[薪火阁]],answer_3 = [[藏书阁]],answer_4 = [[文曲阁]],key = 1,},
						[111] = {id = 111,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:龙山历9669年3月3日谁成为了夏族新的半神？]],answer_1 = [[池丘白]],answer_2 = [[贺源]],answer_3 = [[晁青]],answer_4 = [[陈宫主]],key = 1,},
						[112] = {id = 112,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个不是特殊生死任务？]],answer_1 = [[登云塔]],answer_2 = [[登山路]],answer_3 = [[天穹牢狱]],answer_4 = [[地底岩浆河]],key = 1,},
						[113] = {id = 113,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在登山路任务中领悟了什么真意雏形？]],answer_1 = [[极点穿透]],answer_2 = [[虚界真意]],answer_3 = [[阴阳真意]],answer_4 = [[大地真意]],key = 1,},
						[114] = {id = 114,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:根据夏族的情报，恶魔按照实力被划分为几阶？]],answer_1 = [[五阶]],answer_2 = [[六阶]],answer_3 = [[七阶]],answer_4 = [[八阶]],key = 1,},
						[115] = {id = 115,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:在离开赤云山世界前1天，东伯雪鹰挑战了什么任务？]],answer_1 = [[百战密室]],answer_2 = [[登山路]],answer_3 = [[天穹牢狱]],answer_4 = [[地底岩浆河]],key = 1,},
						[116] = {id = 116,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在六十岁前突破到了什么境界？]],answer_1 = [[圣级]],answer_2 = [[神级]],answer_3 = [[半神级]],answer_4 = [[称号级]],key = 1,},
						[117] = {id = 117,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:星云火石枪是什么品阶的枪？]],answer_1 = [[半神阶]],answer_2 = [[神阶]],answer_3 = [[九品]],answer_4 = [[八品]],key = 1,},
						[118] = {id = 118,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:陈宫主送给东伯雪鹰的镇族之宝是什么？]],answer_1 = [[神界战兵]],answer_2 = [[戒指]],answer_3 = [[水火荡云袍]],answer_4 = [[星云火石枪]],key = 1,},
						[119] = {id = 119,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰是哪个行省的人？]],answer_1 = [[安阳行省]],answer_2 = [[南琴行省]],answer_3 = [[刚铎行省]],answer_4 = [[北多行省]],key = 1,},
						[120] = {id = 120,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个名词不是用来区分境界的？]],answer_1 = [[法师]],answer_2 = [[流星]],answer_3 = [[银月]],answer_4 = [[半神]],key = 1,},
						[121] = {id = 121,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:长风骑士是下面人物中哪一位？]],answer_1 = [[池丘白]],answer_2 = [[晁青]],answer_3 = [[项庞云]],answer_4 = [[司良红]],key = 1,},
						[122] = {id = 122,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:白源之大法师是谁的恩师？]],answer_1 = [[东青石]],answer_2 = [[东伯雪鹰]],answer_3 = [[宗凌]],answer_4 = [[铜三]],key = 1,},
						[123] = {id = 123,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰的初恋是谁？]],answer_1 = [[孔悠月]],answer_2 = [[姬容]],answer_3 = [[余靖秋]],answer_4 = [[程灵淑]],key = 1,},
						[124] = {id = 124,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:守卫黑风渊入口的生物是下面物种中的哪一个？]],answer_1 = [[黑龙]],answer_2 = [[蜘蛛女皇]],answer_3 = [[蝎子]],answer_4 = [[四翼秃鹫]],key = 1,},
						[125] = {id = 125,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:丘池白领悟的真意是下列中的哪一个？]],answer_1 = [[空间切割真意]],answer_2 = [[水浪真意]],answer_3 = [[阴阳真意]],answer_4 = [[星辰真意]],key = 1,},
						[126] = {id = 126,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在超凡之前领悟的第一个奥妙是？]],answer_1 = [[水之奥妙]],answer_2 = [[火之奥妙]],answer_3 = [[风之奥妙]],answer_4 = [[土之奥妙]],key = 1,},
						[127] = {id = 127,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下列人物中的哪一位不是半神级高手？]],answer_1 = [[贝鲁领主]],answer_2 = [[晁青]],answer_3 = [[贺源]],answer_4 = [[步城主]],key = 1,},
						[128] = {id = 128,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下列人物中的哪一位不是圣级高手？]],answer_1 = [[铜三]],answer_2 = [[贝鲁领主]],answer_3 = [[血魔神]],answer_4 = [[涂亮]],key = 1,},
						[129] = {id = 129,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个不是东伯雪鹰的同门师兄弟？]],answer_1 = [[程灵淑]],answer_2 = [[司徒鸿]],answer_3 = [[余风]],answer_4 = [[卓依]],key = 1,},
						[130] = {id = 130,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:动物园里谁是百兽之王?]],answer_1 = [[园长]],answer_2 = [[狮子]],answer_3 = [[老虎]],answer_4 = [[猩猩]],key = 1,},
						[131] = {id = 131,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:人们最早是从那种动物身上得知咖啡的作用?]],answer_1 = [[羊]],answer_2 = [[狮子]],answer_3 = [[老虎]],answer_4 = [[猩猩]],key = 1,},
						[132] = {id = 132,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:门神一个是蔚迟恭，另一个是?]],answer_1 = [[秦琼]],answer_2 = [[程咬金]],answer_3 = [[李白]],answer_4 = [[王世充]],key = 1,},
						[133] = {id = 133,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:宋词名句“天不老，情难绝心似双丝网，中有千千结”作者是?]],answer_1 = [[张生]],answer_2 = [[崔莺莺]],answer_3 = [[辛弃疾]],answer_4 = [[苏东坡]],key = 1,},
						[134] = {id = 134,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:地球上什么动物最大?]],answer_1 = [[蓝鲸]],answer_2 = [[大象]],answer_3 = [[长颈鹿]],answer_4 = [[鲨鱼]],key = 1,},
						[135] = {id = 135,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:“碧云天，黄叶地，北雁南飞”是语出?]],answer_1 = [[西厢记]],answer_2 = [[城南旧事]],answer_3 = [[东厢记]],answer_4 = [[杜十娘]],key = 1,},
						[136] = {id = 136,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰在赤云山悟出了下面哪种奥妙？]],answer_1 = [[风之奥妙]],answer_2 = [[水之奥妙]],answer_3 = [[木之奥妙]],answer_4 = [[金之奥妙]],key = 1,},
						[137] = {id = 137,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个不是赤云山的神界战兵?]],answer_1 = [[杖师傅]],answer_2 = [[刀师父]],answer_3 = [[盾师父]],answer_4 = [[枪师父]],key = 1,},
						[138] = {id = 138,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:袁青领悟的真意是下面真意中的哪一种？]],answer_1 = [[光暗真意]],answer_2 = [[水浪真意]],answer_3 = [[空间切割]],answer_4 = [[虚界真意]],key = 1,},
						[139] = {id = 139,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:是谁孤身杀入了小超凡世界，带领了夏族的反攻？]],answer_1 = [[东伯雪鹰]],answer_2 = [[东伯青石]],answer_3 = [[晁青]],answer_4 = [[贺源]],key = 1,},
						[140] = {id = 140,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰用了几招击败了凶巫战兵？]],answer_1 = [[一招]],answer_2 = [[两招]],answer_3 = [[三招]],answer_4 = [[四招]],key = 1,},
						[141] = {id = 141,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:余靖秋掌握的神心是下面哪一种？]],answer_1 = [[元寒神心]],answer_2 = [[穿透神心]],answer_3 = [[虚界神心]],answer_4 = [[世界神心]],key = 1,},
						[142] = {id = 142,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:神界府城之战一共分为几轮？]],answer_1 = [[三轮]],answer_2 = [[四轮]],answer_3 = [[五轮]],answer_4 = [[六轮]],key = 1,},
						[143] = {id = 143,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一个阶段不在府城之战的赛制之中？]],answer_1 = [[循环战]],answer_2 = [[排序战]],answer_3 = [[擂台战]],answer_4 = [[生存战]],key = 1,},
						[144] = {id = 144,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰是利用什么真意突破黑风神宫的禁制的？]],answer_1 = [[虚界真意]],answer_2 = [[极点穿透真意]],answer_3 = [[星辰真意]],answer_4 = [[大地真意]],key = 1,},
						[145] = {id = 145,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰是利用什么真意打败守卫黑风神宫的黑龙的？]],answer_1 = [[星辰真意]],answer_2 = [[虚界真意]],answer_3 = [[极点穿透真意]],answer_4 = [[大地真意]],key = 1,},
						[146] = {id = 146,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰是被谁出卖然后陷入魔兽一族的包围的？]],answer_1 = [[袁青]],answer_2 = [[东伯青石]],answer_3 = [[晁青]],answer_4 = [[贺源]],key = 1,},
						[147] = {id = 147,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:来自黑暗深渊的队伍的领头的人是谁？]],answer_1 = [[尤兰领主]],answer_2 = [[诺诺暗]],answer_3 = [[炎泽将军]],answer_4 = [[乌炎火]],key = 1,},
						[148] = {id = 148,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:夏族超凡酆东是被谁杀死的？]],answer_1 = [[尤兰领主]],answer_2 = [[诺诺暗]],answer_3 = [[炎泽将军]],answer_4 = [[乌炎火]],key = 1,},
						[149] = {id = 149,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:东伯雪鹰杀死的第一个尤兰领主的手下是谁？]],answer_1 = [[诺诺暗]],answer_2 = [[炎泽将军]],answer_3 = [[乌炎火]],answer_4 = [[库蒙将军]],key = 1,},
						[150] = {id = 150,content = [[（你挖宝到了一个宝箱，但是宝箱中出现了一只守护兽）想得到我的宝藏，先回答我:下面哪一位不是东伯雪鹰的师兄弟？]],answer_1 = [[公良远]],answer_2 = [[贺飞云]],answer_3 = [[余风]],answer_4 = [[戈白]],key = 1,},
					},
					player = {
						[1] = {minLev = 20,maxLev = 60,taskroom = 1,},
						[2] = {minLev = 61,maxLev = 80,taskroom = 2,},
						[3] = {minLev = 81,maxLev = 90,taskroom = 3,},
						[4] = {minLev = 91,maxLev = 100,taskroom = 4,},
						[5] = {minLev = 101,maxLev = 110,taskroom = 5,},
						[6] = {minLev = 111,maxLev = 120,taskroom = 6,},
						[7] = {minLev = 121,maxLev = 200,taskroom = 7,},
					},
					taskroom = {
						[1] = {taskroom = 1,
							task = {
								[1] = {taskId = 1002,monsterId = 106002,name = [[巨剑守卫]],num = 100,scene = 6007,point = [[89,46]],},
								[2] = {taskId = 1003,monsterId = 106003,name = [[金色猿猴]],num = 100,scene = 6007,point = [[50,26]],},
								[3] = {taskId = 1004,monsterId = 106005,name = [[血玉蜘蛛]],num = 100,scene = 6007,point = [[76,153]],},
							},
						},
						[2] = {taskroom = 2,
							task = {
								[1] = {taskId = 2001,monsterId = 107001,name = [[流氓]],num = 100,scene = 6008,point = [[49,264]],},
								[2] = {taskId = 2002,monsterId = 107002,name = [[流氓]],num = 100,scene = 6008,point = [[102,292]],},
								[3] = {taskId = 2003,monsterId = 107003,name = [[土著居民]],num = 100,scene = 6008,point = [[73.0,204.0]],},
								[4] = {taskId = 2004,monsterId = 107004,name = [[魔神会护卫]],num = 100,scene = 6008,point = [[135,40]],},
								[5] = {taskId = 2006,monsterId = 107006,name = [[公良府奴仆]],num = 100,scene = 6008,point = [[192,381]],},
								[6] = {taskId = 2007,monsterId = 107007,name = [[擂台武师]],num = 100,scene = 6008,point = [[250,113]],},
								[7] = {taskId = 2009,monsterId = 107009,name = [[恶魔余孽]],num = 100,scene = 6008,point = [[72,153]],},
								[8] = {taskId = 2010,monsterId = 107010,name = [[魔族余孽]],num = 100,scene = 6008,point = [[285,203]],},
							},
						},
						[3] = {taskroom = 3,
							task = {
								[1] = {taskId = 4001,monsterId = 109001,name = [[盾师父]],num = 230,scene = 6010,point = [[82.8,36.3]],},
								[2] = {taskId = 4002,monsterId = 109002,name = [[枪师父]],num = 230,scene = 6010,point = [[38.1,83.1]],},
								[3] = {taskId = 4003,monsterId = 109003,name = [[弓师父]],num = 230,scene = 6010,point = [[66.7,141.3]],},
								[4] = {taskId = 4004,monsterId = 109004,name = [[毒师父]],num = 230,scene = 6010,point = [[118.6,206.9]],},
								[5] = {taskId = 4005,monsterId = 109005,name = [[锤师父]],num = 230,scene = 6010,point = [[11.8,155.1]],},
							},
						},
						[4] = {taskroom = 4,
							task = {
								[1] = {taskId = 5001,monsterId = 109101,name = [[恶魔战士]],num = 100,scene = 6011,point = [[28,50]],},
								[2] = {taskId = 5003,monsterId = 109103,name = [[恶魔守卫]],num = 100,scene = 6011,point = [[67,6]],},
								[3] = {taskId = 5005,monsterId = 109105,name = [[连心恶魔]],num = 100,scene = 6011,point = [[94,25]],},
								[4] = {taskId = 5007,monsterId = 109107,name = [[恶魔狂战士]],num = 100,scene = 6011,point = [[58,115]],},
								[5] = {taskId = 5010,monsterId = 109110,name = [[恶魔巫师]],num = 100,scene = 6011,point = [[105,70]],},
							},
						},
						[5] = {taskroom = 5,
							task = {
								[1] = {taskId = 6001,monsterId = 109201,name = [[荒原蛇女]],num = 100,scene = 6015,point = [[20,24]],},
								[2] = {taskId = 6002,monsterId = 109202,name = [[荒原战兽]],num = 100,scene = 6015,point = [[36,74]],},
								[3] = {taskId = 6003,monsterId = 109203,name = [[荒原毒蝎]],num = 100,scene = 6015,point = [[31,214]],},
								[4] = {taskId = 6004,monsterId = 109204,name = [[荒原秃鹫]],num = 100,scene = 6015,point = [[108,79]],},
								[5] = {taskId = 6005,monsterId = 109205,name = [[荒原雄狮]],num = 100,scene = 6015,point = [[105,213]],},
							},
						},
						[6] = {taskroom = 6,
							task = {
								[1] = {taskId = 7001,monsterId = 109301,name = [[魔神会喽啰]],num = 100,scene = 6016,point = [[118,49]],},
								[2] = {taskId = 7002,monsterId = 109302,name = [[魔神会精英]],num = 100,scene = 6016,point = [[101,87]],},
								[3] = {taskId = 7004,monsterId = 109304,name = [[魔神会祭司]],num = 100,scene = 6016,point = [[42,85]],},
								[4] = {taskId = 7005,monsterId = 109305,name = [[魔神会圣女]],num = 100,scene = 6016,point = [[56,179]],},
								[5] = {taskId = 7006,monsterId = 109306,name = [[魔神会死士]],num = 100,scene = 6016,point = [[33,130]],},
							},
						},
						[7] = {taskroom = 7,
							task = {
								[1] = {taskId = 8001,monsterId = 109401,name = [[海神宫守卫]],num = 100,scene = 6018,point = [[127,51]],},
								[2] = {taskId = 8002,monsterId = 109402,name = [[海神宫女弟子]],num = 100,scene = 6018,point = [[85,90]],},
								[3] = {taskId = 8004,monsterId = 109404,name = [[魔化侍卫]],num = 100,scene = 6018,point = [[49,186]],},
							},
						},
					},
				},
			},
		},
	},
}
