_guidefunction_Info = {
	root = {
		[1] = {
			["function"] = {
				[1] = {id = 651,functionid = 447,guideid = 447,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 2,name = [[神界战兵]],},
				[2] = {id = 1191,functionid = 1191,guideid = 1191,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 3,name = [[法阵]],},
				[3] = {id = 1215,functionid = 3000,guideid = 1190,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 4,name = [[披风]],},
				[4] = {id = 459,functionid = 459,guideid = 459,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 5,name = [[界兵]],},
				[5] = {id = 100,functionid = 100,guideid = 100,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 6,name = [[战骑]],},
				[6] = {id = 461,functionid = 461,guideid = 461,lev = [[]],quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = 7,name = [[战羽]],},
				[7] = {id = 9,functionid = 5001,guideid = 226,lev = [[]],quest = 10010230,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[龙山帝宝]],},
				[8] = {id = 40,functionid = 401,guideid = 401,lev = [[]],quest = 10060100,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[神兵]],},
				[9] = {id = 50,functionid = 400,guideid = 400,lev = [[]],quest = 10010171,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[坐骑]],},
				[10] = {id = 55,functionid = 112,guideid = 112,lev = [[]],quest = 10010180,isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[骑乘]],},
				[11] = {id = 56,functionid = [[]],guideid = 1400,lev = [[]],quest = 10010270,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[坐骑进阶]],},
				[12] = {id = 70,functionid = 1010,guideid = 1010,lev = [[]],quest = 10020175,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[伙伴开启]],},
				[13] = {id = 85,functionid = [[]],guideid = 257,lev = [[]],quest = 10070090,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[七日登录]],},
				[14] = {id = 90,functionid = 116,guideid = 116,lev = [[]],quest = 10050080,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备强化]],},
				[15] = {id = 91,functionid = 117,guideid = 117,lev = [[]],quest = 10070150,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备宝石]],},
				[16] = {id = 120,functionid = [[]],guideid = 1011,lev = [[]],quest = 10050171,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[伙伴进阶]],},
				[17] = {id = 130,functionid = 204,guideid = 204,lev = [[]],quest = 10010190,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[首充]],},
				[18] = {id = 140,functionid = 408,guideid = 408,lev = [[]],quest = 10060010,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备升级]],},
				[19] = {id = 200,functionid = 201,guideid = 201,lev = [[]],quest = 10070161,isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[剧情副本]],},
				[20] = {id = 210,functionid = 200,guideid = 200,lev = [[]],quest = 10070032,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[法宝感悟]],},
				[21] = {id = 230,functionid = 1050,guideid = 1050,lev = [[]],quest = 10070181,isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[经验副本]],},
				[22] = {id = 240,functionid = 1040,guideid = 1040,lev = [[]],quest = 10070215,isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[超凡生死战]],},
				[23] = {id = 250,functionid = 106,guideid = 106,lev = [[]],quest = 10060040,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[家族]],},
				[24] = {id = 280,functionid = 1030,guideid = 1030,lev = 999,quest = [[]],isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[登山路]],},
				[25] = {id = 421,functionid = [[]],guideid = 421,lev = [[]],quest = 10070124,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[龙山巡守引导]],},
				[26] = {id = 650,functionid = 650,guideid = 650,lev = [[]],quest = 10060021,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[抢红包]],},
				[27] = {id = 807,functionid = 807,guideid = 807,lev = [[]],quest = 10020053,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[境界]],},
				[28] = {id = 1060,functionid = 5063,guideid = 1063,lev = [[]],quest = 10070190,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[结婚]],},
				[29] = {id = 1217,functionid = 602,guideid = 612,lev = [[]],quest = 10070041,isend = 0,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[进阶副本]],},
				[30] = {id = 1330,functionid = 402,guideid = 402,lev = [[]],quest = 10090061,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[羽翼进阶]],},
				[31] = {id = 11,functionid = 5002,guideid = 11,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[守卫夏族]],},
				[32] = {id = 12,functionid = 612,guideid = 445,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[神装收集]],},
				[33] = {id = 20,functionid = 103,guideid = 103,lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[技能]],},
				[34] = {id = 30,functionid = 300,guideid = 300,lev = 2,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[跳跃]],},
				[35] = {id = 72,functionid = 1195,guideid = 1195,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[进阶排行榜]],},
				[36] = {id = 80,functionid = 256,guideid = 256,lev = 20,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[七日登录]],},
				[37] = {id = 110,functionid = 206,guideid = 206,lev = 25,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[签到]],},
				[38] = {id = 160,functionid = 501,guideid = 501,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[日常任务]],},
				[39] = {id = 180,functionid = 209,guideid = 209,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[龙山商行]],},
				[40] = {id = 220,functionid = 418,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[单服竞技场]],},
				[41] = {id = 221,functionid = [[]],guideid = 463,lev = [[]],quest = 10070022,isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[单服竞技场]],},
				[42] = {id = 225,functionid = 225,guideid = 225,lev = 55,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[交易行]],},
				[43] = {id = 260,functionid = 1120,guideid = 1120,lev = 30,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[领主特权]],},
				[44] = {id = 424,functionid = 424,guideid = 424,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[首充团购]],},
				[45] = {id = 426,functionid = 426,guideid = 426,lev = 54,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[跨服副本]],},
				[46] = {id = 431,functionid = 431,guideid = 431,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[连充返利]],},
				[47] = {id = 444,functionid = 444,guideid = 444,lev = 53,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[图鉴任务]],},
				[48] = {id = 446,functionid = 5003,guideid = 446,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[图鉴]],},
				[49] = {id = 460,functionid = 460,guideid = 460,lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[成就]],},
				[50] = {id = 462,functionid = 462,guideid = 462,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[进阶日]],},
				[51] = {id = 551,functionid = 551,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[挂机任务]],},
				[52] = {id = 560,functionid = 560,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[家族boss]],},
				[53] = {id = 561,functionid = 561,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[家族聚餐]],},
				[54] = {id = 562,functionid = 562,guideid = 562,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[世界BOSS]],},
				[55] = {id = 566,functionid = 566,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[VIP副本]],},
				[56] = {id = 570,functionid = 570,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[元宝大作战]],},
				[57] = {id = 615,functionid = 615,guideid = 615,lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[贵族]],},
				[58] = {id = 1020,functionid = 327,guideid = 327,lev = 59,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备精炼]],},
				[59] = {id = 1040,functionid = 5067,guideid = 1067,lev = 56,quest = [[]],isend = 1,realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备洗练]],},
				[60] = {id = 1050,functionid = 514,guideid = 514,lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[时装]],},
				[61] = {id = 1070,functionid = 211,guideid = 211,lev = 54,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[护送任务]],},
				[62] = {id = 1090,functionid = 113,guideid = 113,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[打坐]],},
				[63] = {id = 1100,functionid = 705,guideid = 705,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[排行榜]],},
				[64] = {id = 1110,functionid = 5057,guideid = 1057,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[智力答题]],},
				[65] = {id = 1120,functionid = 500,guideid = 500,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[药浴]],},
				[66] = {id = 1125,functionid = 2000,guideid = 1180,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[多倍挂机]],},
				[67] = {id = 1130,functionid = 5058,guideid = 1058,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[神魔降临]],},
				[68] = {id = 1140,functionid = 700,guideid = 700,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[黑风神宫]],},
				[69] = {id = 1150,functionid = 5059,guideid = 1059,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[城战]],},
				[70] = {id = 1160,functionid = 1100,guideid = 1100,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[夏族演兵]],},
				[71] = {id = 1170,functionid = 5061,guideid = 1061,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[更新公告]],},
				[72] = {id = 1200,functionid = 207,guideid = 207,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[返利大厅]],},
				[73] = {id = 1210,functionid = 504,guideid = 504,lev = 45,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[开服活动]],},
				[74] = {id = 1220,functionid = 1090,guideid = 1090,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[支线任务]],},
				[75] = {id = 1230,functionid = 203,guideid = 203,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[活动大厅]],},
				[76] = {id = 1240,functionid = 420,guideid = 420,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[龙山巡守]],},
				[77] = {id = 1250,functionid = 419,guideid = 419,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[我要变强]],},
				[78] = {id = 1260,functionid = 513,guideid = 513,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[节日活动]],},
				[79] = {id = 1270,functionid = 5064,guideid = 1064,lev = 80,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[跨服排行榜]],},
				[80] = {id = 1280,functionid = 5065,guideid = 1065,lev = 70,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[资源找回]],},
				[81] = {id = 1290,functionid = 5066,guideid = 1066,lev = 70,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[离线经验]],},
				[82] = {id = 1310,functionid = 5068,guideid = 1068,lev = 80,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[世界等级]],},
				[83] = {id = 1340,functionid = 5069,guideid = 1103,lev = 65,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[跨服boss]],},
				[84] = {id = 1351,functionid = 5090,guideid = 457,lev = 39,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[开服基金-新]],},
				[85] = {id = 1360,functionid = 1060,guideid = 1060,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[薪火幻域]],},
				[86] = {id = 1370,functionid = 701,guideid = 701,lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[37盒子]],},
				[87] = {id = 1371,functionid = 702,guideid = [[]],lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[2144游戏大厅]],},
				[88] = {id = 1372,functionid = 703,guideid = [[]],lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[迅雷游戏盒子]],},
				[89] = {id = 1373,functionid = 350,guideid = [[]],lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[越南vTc]],},
				[90] = {id = 1380,functionid = 5060,guideid = 1160,lev = 51,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[炼化]],},
				[91] = {id = 1390,functionid = 5000,guideid = 1201,lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[战场大厅]],},
				[92] = {id = 1400,functionid = 750,guideid = [[]],lev = 1,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[微端]],},
				[93] = {id = 1500,functionid = 1500,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[开服拍卖]],},
				[94] = {id = 1501,functionid = 1501,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[进阶投资]],},
				[95] = {id = 1502,functionid = 1502,guideid = [[]],lev = 50,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备兑换]],},
				[96] = {id = 1503,functionid = 1503,guideid = [[]],lev = 65,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[家族任务]],},
				[97] = {id = 1504,functionid = 1504,guideid = [[]],lev = 60,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[装备熔炼]],},
				[98] = {id = 70,functionid = 1194,guideid = 1194,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],qiriday = [[]],name = [[跨服1V1暂时不要]],},
				[99] = {id = 1141,functionid = 603,guideid = 603,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[黑风遗宝暂时不要]],},
				[100] = {id = 427,functionid = 427,guideid = 427,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[功能预告暂时不要]],},
				[101] = {id = 1180,functionid = 600,guideid = 600,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[黑风遗宝暂时不要]],},
				[102] = {id = 71,functionid = 2100,guideid = 620,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[伙伴冒险暂时不要]],},
				[103] = {id = 428,functionid = 428,guideid = 428,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[紫雷药园暂时不要]],},
				[104] = {id = 170,functionid = 5100,guideid = 1200,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[单人副本暂时不要]],},
				[105] = {id = 1000,functionid = 5056,guideid = 1056,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[装备属性转移暂时不要]],},
				[106] = {id = 1030,functionid = 405,guideid = 405,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[装备提品暂时不要]],},
				[107] = {id = 455,functionid = 455,guideid = 455,lev = 200,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[帝宝精炼暂时不要]],},
				[108] = {id = 270,functionid = 544,guideid = 544,lev = 200,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[夏都宝库暂时不要]],},
				[109] = {id = 1320,functionid = 5102,guideid = 1102,lev = 200,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[完美境界暂时不要]],},
				[110] = {id = 1350,functionid = 5104,guideid = 1104,lev = 200,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[红石山暂时不要]],},
				[111] = {id = 155,functionid = 800,guideid = 800,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[血脉暂时不要]],},
				[112] = {id = 210,functionid = 210,guideid = 210,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[萌宠暂时不要]],},
				[113] = {id = 150,functionid = 1020,guideid = 1020,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[真意暂时不要]],},
				[114] = {id = 100,functionid = 1070,guideid = 1070,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[神兵熟练不要]],},
				[115] = {id = 1216,functionid = 601,guideid = 611,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[洞天法宝不要]],},
				[116] = {id = 456,functionid = 456,guideid = 456,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[成神之路不要]],},
				[117] = {id = 710,functionid = 710,guideid = 710,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[银两副本不要]],},
				[118] = {id = 425,functionid = 425,guideid = 425,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[奇遇寻宝不要]],},
				[119] = {id = 1135,functionid = 430,guideid = 430,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[元宝免费送不要]],},
				[120] = {id = 447,functionid = 5004,guideid = [[]],lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[番茄宝藏不要]],},
				[121] = {id = 1190,functionid = 5062,guideid = 1062,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[全民反馈不要]],},
				[122] = {id = 1380,functionid = 5070,guideid = 1170,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[消费折扣不要]],},
				[123] = {id = 432,functionid = 432,guideid = 432,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[元宝翻倍不要]],},
				[124] = {id = 1218,functionid = 1193,guideid = 1193,lev = 999,quest = [[]],isend = [[]],realm = [[]],stage = [[]],vip = [[]],name = [[伙伴副本不要]],},
			},
		},
	},
}
