_open_advanceday_Info = {
	root = {
		[1] = {
			server = {
				[1] = {servernum = -1,
					wealth = {
						[1] = {day = 9999,activityid = 1,},
						[2] = {day = 9999,activityid = 2,},
						[3] = {day = 9999,activityid = 10,},
						[4] = {day = 9999,activityid = 3,},
						[5] = {day = 9999,activityid = 4,},
						[6] = {day = 9999,activityid = 5,},
					},
					activity = {
						[1] = {activityid = 1,background = [[openadvance]],left_title = [[zuoqi]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 101001,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950003,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 101001,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950003,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 2060105,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 101001,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950003,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 101001,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110002,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190174,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 101001,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110003,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060105,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
						[2] = {activityid = 2,background = [[openadvance]],left_title = [[shenbing]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 900007,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950001,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 900007,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950001,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 900007,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950001,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 900007,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110202,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190175,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 900007,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110203,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060110,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
						[3] = {activityid = 3,background = [[openadvance]],left_title = [[yuyi]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 101501,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950004,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 101501,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950004,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 101501,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950004,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 101501,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110102,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190176,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 101501,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110103,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060109,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
						[4] = {activityid = 4,background = [[openadvance]],left_title = [[pifeng]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 108001,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950005,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 108001,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950005,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 108001,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950005,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 108001,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110302,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190179,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 108001,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110303,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060108,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
						[5] = {activityid = 5,background = [[openadvance]],left_title = [[fazhen]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 106001,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950006,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 106001,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950006,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 106001,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950006,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 106001,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110402,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190178,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 106001,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110403,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060106,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
						[6] = {activityid = 10,background = [[openadvance]],left_title = [[huoban]],
							advance = {
								[1] = {level = 2,text = [[]],
									reward = {
										[1] = {item = 109501,itemnum = 4,bind = 1,timemode = 0,},
										[2] = {item = 950012,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[2] = {level = 3,text = [[]],
									reward = {
										[1] = {item = 109501,itemnum = 8,bind = 1,timemode = 0,},
										[2] = {item = 950012,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[3] = {level = 4,text = [[]],
									reward = {
										[1] = {item = 109501,itemnum = 14,bind = 1,timemode = 0,},
										[2] = {item = 950012,itemnum = 2,bind = 1,timemode = 0,},
									},
								},
								[4] = {level = 5,text = [[]],
									reward = {
										[1] = {item = 109501,itemnum = 20,bind = 1,timemode = 0,},
										[2] = {item = 110902,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 190177,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
								[5] = {level = 6,text = [[]],
									reward = {
										[1] = {item = 109501,itemnum = 36,bind = 1,timemode = 0,},
										[2] = {item = 110903,itemnum = 1,bind = 1,timemode = 0,},
										[3] = {item = 3060102,itemnum = 1,bind = 1,timemode = 0,},
									},
								},
							},
						},
					},
				},
			},
		},
	},
}
